# NAME-PAPU SWAIN

### PROJECT-01(Mercedes-Benz Greener Manufacturing)

#### DOMAIN-PRODUCTION/MANUFACTURING

OBJECTIVE-You are required to reduce the time that cars spend on the test bench. Others will work with a dataset representing different permutations of features in a Mercedes-Benz car to predict the time it takes to pass testing. Optimal algorithms will contribute to faster testing, resulting in lower carbon dioxide emissions without reducing Mercedes-Benz’s standards.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
train=pd.read_csv("train1.csv")
test=pd.read_csv("test1.csv")

In [3]:
train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [5]:
test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [6]:
train.drop(columns="ID",inplace=True)
test.drop(columns="ID",inplace=True)

In [7]:
train.shape,test.shape

((4209, 377), (4209, 376))

## Remove columns having zero variance

In [18]:
zero_var_col=train.var()[train.var()==0].index.values
zero_var_col

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [19]:
train.drop(zero_var_col,axis=1,inplace=True)
test.drop(zero_var_col,axis=1,inplace=True)

In [20]:
train.shape,test.shape

((4209, 365), (4209, 364))

## Checking of null values in Train and Test dataset

In [22]:
train.isna().sum()

y       0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 365, dtype: int64

In [24]:
np.sum(train.isna().sum())

0

In [25]:
test.isna().sum().sum()

0

## Checking of  unique values in Train and Test dataset

In [26]:
train.describe(include="all").T

count unique  top  freq        mean        std    min    25%    50%  \
y     4209.0    NaN  NaN   NaN  100.669318  12.679381  72.11  90.82  99.15   
X0      4209     47    z   360         NaN        NaN    NaN    NaN    NaN   
X1      4209     27   aa   833         NaN        NaN    NaN    NaN    NaN   
X2      4209     44   as  1659         NaN        NaN    NaN    NaN    NaN   
X3      4209      7    c  1942         NaN        NaN    NaN    NaN    NaN   
...      ...    ...  ...   ...         ...        ...    ...    ...    ...   
X380  4209.0    NaN  NaN   NaN    0.008078   0.089524    0.0    0.0    0.0   
X382  4209.0    NaN  NaN   NaN    0.007603   0.086872    0.0    0.0    0.0   
X383  4209.0    NaN  NaN   NaN    0.001663   0.040752    0.0    0.0    0.0   
X384  4209.0    NaN  NaN   NaN    0.000475   0.021796    0.0    0.0    0.0   
X385  4209.0    NaN  NaN   NaN    0.001426   0.037734    0.0    0.0    0.0   

         75%     max  
y     109.01  265.32  
X0       NaN     NaN  
X1       NaN     NaN  
X2       NaN     NaN  
X3       NaN     NaN  
...      ...     ...  
X380     0.0     1.0  
X382     0.0     1.0  
X383     0.0     1.0  
X384     0.0     1.0  
X385     0.0     1.0  

[365 rows x 11 columns]

In [27]:
train.nunique()

y       2545
X0        47
X1        27
X2        44
X3         7
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 365, dtype: int64

In [28]:
test.nunique()

X0      49
X1      27
X2      45
X3       7
X4       4
        ..
X380     2
X382     2
X383     2
X384     2
X385     2
Length: 364, dtype: int64

In [29]:
for i in train:
    print("\nThe unique values in column ",i)
    print(train[i].unique())


The unique values in column  y
[130.81  88.53  76.26 ...  85.71 108.77  87.48]

The unique values in column  X0
['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab']

The unique values in column  X1
['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab']

The unique values in column  X2
['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar']

The unique values in column  X3
['a' 'e' 'c' 'f' 'd' 'b' 'g']

The unique values in column  X4
['d' 'b' 'c' 'a']

The unique values in column  X5
['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad' 'ae'
 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa']

The unique values 

The unique values in column  X355
[0 1]

The unique values in column  X356
[0 1]

The unique values in column  X357
[0 1]

The unique values in column  X358
[0 1]

The unique values in column  X359
[0 1]

The unique values in column  X360
[0 1]

The unique values in column  X361
[1 0]

The unique values in column  X362
[0 1]

The unique values in column  X363
[0 1]

The unique values in column  X364
[0 1]

The unique values in column  X365
[0 1]

The unique values in column  X366
[0 1]

The unique values in column  X367
[0 1]

The unique values in column  X368
[0 1]

The unique values in column  X369
[0 1]

The unique values in column  X370
[0 1]

The unique values in column  X371
[0 1]

The unique values in column  X372
[0 1]

The unique values in column  X373
[0 1]

The unique values in column  X374
[0 1]

The unique values in column  X375
[0 1]

The unique values in column  X376
[0 1]

The unique values in column  X377
[1 0]

The unique values in column  X378
[0 1]

The unique value

In [30]:
for i in test:
    print("\nThe unique values in column ",i)
    print(test[i].unique())


The unique values in column  X0
['az' 't' 'w' 'y' 'x' 'f' 'ap' 'o' 'ay' 'al' 'h' 'z' 'aj' 'd' 'v' 'ak'
 'ba' 'n' 'j' 's' 'af' 'ax' 'at' 'aq' 'av' 'm' 'k' 'a' 'e' 'ai' 'i' 'ag'
 'b' 'am' 'aw' 'as' 'r' 'ao' 'u' 'l' 'c' 'ad' 'au' 'bc' 'g' 'an' 'ae' 'p'
 'bb']

The unique values in column  X1
['v' 'b' 'l' 's' 'aa' 'r' 'a' 'i' 'p' 'c' 'o' 'm' 'z' 'e' 'h' 'w' 'g' 'k'
 'y' 't' 'u' 'd' 'j' 'q' 'n' 'f' 'ab']

The unique values in column  X2
['n' 'ai' 'as' 'ae' 's' 'b' 'e' 'ak' 'm' 'a' 'aq' 'ag' 'r' 'k' 'aj' 'ay'
 'ao' 'an' 'ac' 'af' 'ax' 'h' 'i' 'f' 'ap' 'p' 'au' 't' 'z' 'y' 'aw' 'd'
 'at' 'g' 'am' 'j' 'x' 'ab' 'w' 'q' 'ah' 'ad' 'al' 'av' 'u']

The unique values in column  X3
['f' 'a' 'c' 'e' 'd' 'g' 'b']

The unique values in column  X4
['d' 'b' 'a' 'c']

The unique values in column  X5
['t' 'b' 'a' 'z' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac'
 'ad' 'ae' 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa']

The unique values in column  X6
['a' 'g' 'j' 'l' 'i' 'd' 'f' 'h' 'c' 

[0 1]

The unique values in column  X323
[0 1]

The unique values in column  X324
[0 1]

The unique values in column  X325
[0 1]

The unique values in column  X326
[0 1]

The unique values in column  X327
[0 1]

The unique values in column  X328
[1 0]

The unique values in column  X329
[0 1]

The unique values in column  X331
[0 1]

The unique values in column  X332
[0 1]

The unique values in column  X333
[0 1]

The unique values in column  X334
[1 0]

The unique values in column  X335
[0 1]

The unique values in column  X336
[0 1]

The unique values in column  X337
[0 1]

The unique values in column  X338
[0 1]

The unique values in column  X339
[0 1]

The unique values in column  X340
[0 1]

The unique values in column  X341
[0 1]

The unique values in column  X342
[0 1]

The unique values in column  X343
[0 1]

The unique values in column  X344
[0 1]

The unique values in column  X345
[0 1]

The unique values in column  X346
[0 1]

The unique values in column  X348
[1 0]

The uniqu

In [31]:
train.head()

y  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0  130.81   k  v  at  a  d  u  j  o    0  ...     0     0     1     0     0   
1   88.53   k  t  av  e  d  y  l  o    0  ...     1     0     0     0     0   
2   76.26  az  w   n  c  d  x  j  x    0  ...     0     0     0     0     0   
3   80.62  az  t   n  f  d  x  l  e    0  ...     0     0     0     0     0   
4   78.02  az  v   n  f  d  h  d  n    0  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 365 columns]

## Apply Label Encoder to the columns having object datatype

In [19]:
train.describe(include="object")

X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [20]:
object_col=train.describe(include="object").columns.values
object_col

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [21]:
test.describe(include="object").columns.values

array(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype=object)

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label_encoder=LabelEncoder()
for i in object_col:
    label_encoder.fit(train[i].append(test[i]).values)
    train[i]=label_encoder.transform(train[i])
    test[i]=label_encoder.transform(test[i])

In [24]:
train.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  130.81  37  23  20   0   3  27   9  14    0  ...     0     0     1     0   
1   88.53  37  21  22   4   3  31  11  14    0  ...     1     0     0     0   
2   76.26  24  24  38   2   3  30   9  23    0  ...     0     0     0     0   
3   80.62  24  21  38   5   3  30  11   4    0  ...     0     0     0     0   
4   78.02  24  23  38   5   3  14   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 365 columns]

## Building ML model

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x=train.drop(columns="y")
y=train[["y"]]

In [27]:
x.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  37  23  20   0   3  27   9  14    0    0  ...     0     0     1     0   
1  37  21  22   4   3  31  11  14    0    0  ...     1     0     0     0   
2  24  24  38   2   3  30   9  23    0    0  ...     0     0     0     0   
3  24  21  38   5   3  30  11   4    0    0  ...     0     0     0     0   
4  24  23  38   5   3  14   3  13    0    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [28]:
y.head()

y
0  130.81
1   88.53
2   76.26
3   80.62
4   78.02

In [29]:
x.shape,y.shape

((4209, 364), (4209, 1))

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=25)

In [31]:
x_train.shape,x_test.shape

((3367, 364), (842, 364))

In [32]:
y_train.shape,y_test.shape

((3367, 1), (842, 1))

## Perform dimensionality reduction(PCA-Principal Component Analysis)

In [33]:
from sklearn.decomposition import PCA

In [34]:
pca=PCA(n_components=0.95)
pca.fit(x_train)

PCA(n_components=0.95)

In [35]:
pca.n_components_

6

In [36]:
pca.explained_variance_

array([244.75144186, 131.35944864,  78.76792105,  64.48849676,
        49.57626276,   8.34249776])

In [37]:
x_train_pca=pca.fit_transform(x_train)
x_test_pca=pca.transform(x_test)

In [38]:
x_train_pca

array([[-12.47324199,  12.19028043,  11.58230459,   8.1175685 ,
          5.75530775,  -1.95263387],
       [-20.2417758 ,  -5.43497162, -13.63694591,  -2.03555958,
         11.33272505,   4.3515019 ],
       [ 12.47418815,  -3.99976841, -16.40093253,  -8.20864906,
          1.49736095,   3.9430753 ],
       ...,
       [  4.73966776,  -2.75718833,   9.17791124,   5.78784987,
          0.64179659,   3.49621087],
       [ -4.48021997,  -0.917884  ,   3.0746254 ,   2.81126331,
          7.99706073,  -0.89404095],
       [ -1.82279839, -12.9155011 ,   1.81797389,   7.99274857,
         -1.5708532 ,  -4.74910353]])

In [39]:
x_test_pca

array([[-16.88872645,   3.19447396, -15.95968376,  -2.19601887,
         -8.07261563,  -1.88853009],
       [ 24.82492351,   4.5212193 ,  -8.60357218,   6.33048458,
         11.31201254,  -4.14420826],
       [ 10.2526195 ,  -3.76709333,   1.58009514,  -4.52491522,
         -1.35355957,  -4.76284305],
       ...,
       [ 24.46745312,  -6.83241894,  -5.64679581,  -1.32207084,
          2.01314621,  -1.32343827],
       [ 29.41896587,  -7.85361678,   4.12387006,   5.90299044,
          1.29860342,  -1.79359603],
       [  3.93190731, -16.46831485,  -0.97140162,  -5.94175867,
         -9.99516493,   0.38669856]])

In [40]:
pca.explained_variance_ratio_

array([0.40748595, 0.21869996, 0.13114048, 0.10736671, 0.08253937,
       0.0138894 ])

In [41]:
np.sum(pca.explained_variance_ratio_)

0.9611218734170572

## Linear Regression

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
linear_model=LinearRegression()
linear_model.fit(x_train_pca,y_train)

LinearRegression()

In [44]:
pred=linear_model.predict(x_test_pca)
pred

array([[ 99.61026146],
       [106.0442159 ],
       [102.90754491],
       [100.29901535],
       [ 97.82239017],
       [ 99.47818064],
       [ 98.58665607],
       [102.43046177],
       [105.32931458],
       [100.85970459],
       [104.23061373],
       [ 97.50771986],
       [ 98.44608335],
       [103.93688678],
       [105.75999016],
       [100.09305243],
       [ 98.59498764],
       [ 98.43445001],
       [ 97.97340347],
       [102.06504313],
       [ 99.16548367],
       [ 94.86310623],
       [ 98.42795826],
       [102.75219911],
       [ 98.44055799],
       [ 96.61879481],
       [ 98.05697595],
       [104.348063  ],
       [105.17759623],
       [105.14155767],
       [105.35120962],
       [104.18247137],
       [102.30730866],
       [100.31731984],
       [105.54378891],
       [ 98.13527494],
       [ 96.4853577 ],
       [102.47788643],
       [ 99.1829905 ],
       [100.02192751],
       [ 95.14465232],
       [100.48213383],
       [105.20131389],
       [102

In [45]:
from sklearn.metrics import mean_squared_error,r2_score

In [46]:
mean_squared_error(y_pred=pred,y_true=y_test)

146.42332347096547

In [47]:
mean_squared_error(y_pred=pred,y_true=y_test,squared=False)

12.10055054412672

In [48]:
r2_score(y_pred=pred,y_true=y_test)

0.024838075853205743

## Linear Regression using XGBoost

In [49]:
from xgboost import XGBRegressor

In [50]:
xgb_model=XGBRegressor(objective="reg:linear",learning_rate=0.1)
xgb_model.fit(x_train_pca,y_train)

[12:41:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.1, max_delta_step=0,
             max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=4,
             num_parallel_tree=1, objective='reg:linear', predictor='auto',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             subsample=1, tree_method='exact', validate_parameters=1,
             verbosity=None)

In [51]:
xgb_pred=xgb_model.predict(x_test_pca)
xgb_pred

array([102.76453 ,  95.69934 , 105.29932 ,  94.63214 , 109.90327 ,
        96.552345,  93.86191 ,  72.94642 , 104.95297 ,  99.600395,
        98.42066 ,  92.18041 , 100.96305 , 111.032104, 113.75449 ,
       108.9629  , 107.8475  ,  97.01356 , 100.75376 ,  97.95204 ,
        99.49093 ,  92.09597 ,  92.28836 , 100.62599 , 101.75155 ,
       102.5966  ,  93.84322 , 113.14956 ,  94.168175, 109.38829 ,
       100.57961 , 110.661804,  80.1837  ,  95.431335, 111.96438 ,
        97.799255,  94.52357 , 111.21358 , 108.577545,  94.91593 ,
        97.07836 ,  96.00598 , 111.37035 , 103.21014 ,  93.677055,
        90.86232 ,  97.80297 ,  91.87829 , 104.666504, 104.68663 ,
        99.927086, 110.33094 ,  95.80324 ,  95.805916, 105.457794,
        94.7485  ,  91.13829 ,  93.89581 ,  96.7221  ,  96.24189 ,
       119.03503 , 102.17994 ,  94.841545, 109.19207 ,  96.58355 ,
       109.03911 , 106.721504, 122.89397 , 108.18036 ,  95.24458 ,
        97.42552 , 100.71242 ,  95.28053 , 109.953735,  94.102

In [52]:
mean_squared_error(y_pred=xgb_pred,y_true=y_test,squared=False)

9.44352846785231

In [53]:
r2_score(y_pred=xgb_pred,y_true=y_test)

0.4060702725072055

## Random forest using XGBoost

In [54]:
from xgboost import XGBClassifier

In [55]:
xgb_rf_model=XGBClassifier()
xgb_rf_model.fit(x_train_pca,y_train)

[12:41:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=4,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [56]:
xgb_rf_pred=xgb_rf_model.predict(x_test_pca)
xgb_rf_pred

array([ 90.49,  87.86,  98.97,  90.44,  96.45,  99.94, 113.93,  75.85,
       113.39,  97.26, 106.82,  88.23, 116.59, 135.48, 142.71, 110.57,
        91.52,  89.  ,  89.91, 106.59,  93.59,  92.63, 111.55,  96.76,
        88.93,  89.25,  91.52, 130.97,  92.98, 114.8 , 110.07,  97.36,
        84.15, 101.  , 114.26, 113.39,  92.63, 113.93, 108.43,  87.57,
        92.63,  89.67, 104.87, 111.04,  97.32, 106.82, 101.39,  91.99,
       116.28, 106.52,  96.85, 112.67,  94.81, 109.13,  87.33,  91.41,
       100.35,  98.28,  90.4 ,  93.45, 119.78, 104.65,  92.79, 111.86,
        91.11,  88.66,  98.13, 149.63, 100.04,  89.23,  94.91, 106.97,
        97.86,  87.91, 108.99,  88.39,  92.03,  97.98, 106.39, 106.23,
       106.1 ,  95.77,  74.08, 105.82,  74.54,  90.58,  88.78, 101.71,
       102.91, 112.95,  86.61,  99.55, 109.05, 107.39,  93.67, 107.68,
        87.26,  78.25,  98.84, 108.02,  90.38,  93.6 ,  90.65,  92.13,
        90.16,  88.75, 123.17, 103.62, 110.32, 116.93, 108.24,  94.27,
      

In [57]:
mean_squared_error(y_pred=xgb_rf_pred,y_true=y_test,squared=False)

13.193019545458153

#                    THANK YOU!!!